[project]
name = "easy-to-markdown"
version = "0.1.0"
description = ""
authors = [
    {name = "xuanjinliang",email = "xuanjinliang@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11,<4"
dependencies = [
    "doclayout-yolo (>=0.0.4,<0.0.5)",
    "pillow (>=12.2.0,<13.0.0)",
    "opencv-python (>=4.13.0.92,<5.0.0.0)",
    "huggingface-hub (>=1.18.0,<2.0.0)",
    "pymupdf (>=1.27.2.3,<2.0.0.0)",
    "pydantic (>=2.13.4,<3.0.0)",
    "paddleocr[doc-parser] (>=3.7.0,<4.0.0)",
    "paddlex (>=3.7.1,<4.0.0)",
    "dashscope (>=1.25.22,<2.0.0)",
    "numpy (==2.3.5)",
    "accelerate (>=1.14.0,<2.0.0)",
    "transformers (>=5.14.1,<6.0.0)",
    "qwen-vl-utils (>=0.0.14,<0.0.15)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
paddlepaddle = "^3.3.1"

